import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/lib/Providers";
import Navbar from "@/components/common/Navbar";
import { SessionProvider } from "next-auth/react";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IITG Student website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <html lang="en">
      
      <body className={`${inter.className} overflow-x-hidden`}>
      
 
        <Providers>
        <Navbar />
        {children}
        </Providers>
       
    
      </body>
    </html>
  );
}
